# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :ipaserver => {
	:box_name => "centos/7",
	:ip_addr  => '192.168.11.101',
	:mem => 4096
    },
    :ipaclient => {
	:box_name => "centos/7",
	:ip_addr  => '192.168.11.102',
	:mem => 512
    }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
	config.vm.define boxname do |box|

	    box.vm.box = boxconfig[:box_name]
	    box.vm.host_name = boxname.to_s + ".otus.lan"
	    box.vm.network "private_network", ip: boxconfig[:ip_addr]

	    box.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", boxconfig[:mem] ]
	    end

	    box.vm.provision "shell", inline: <<-SHELL
		mkdir -p ~root/.ssh
		cp ~vagrant/.ssh/auth* ~root/.ssh
		sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
		systemctl restart sshd
	    SHELL

	    box.vm.provision "ansible" do |ansible|
		ansible.compatibility_mode = "2.0"
		ansible.become = "true"
		ansible.inventory_path = "staging/hosts"
		ansible.playbook = "playbooks/free-ipa.yml"
	    end

	end

    end

end
