---
- name: rsyslog | enable udp
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#\$ModLoad imudp'
    line: '$ModLoad imudp'
    backrefs: yes
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: rsyslog | set port udp
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#\$UDPServerRun 514'
    line: '$UDPServerRun 514'
    backrefs: yes
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: rsyslog | enable tcp
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#\$ModLoad imtcp'
    line: '$ModLoad imtcp'
    backrefs: yes
  notify:
    - restart rsyslog
  tags:
    - rsyslog

- name: rsyslog | set port tcp
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^#\$InputTCPServerRun 514'
    line: '$InputTCPServerRun 514'
    backrefs: yes
  notify:
    - restart rsyslog
  tags:
    - rsyslog
