---
- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    enabled: yes

- name: restart logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes
