# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.hostname = "www"
    config.vm.box = "centos/7"
    config.vm.network "forwarded_port", guest: 80, host: 8081
    config.vm.define "www"
    config.vm.provider :virtualbox do |vb|
	vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    config.vm.provision "ansible" do |ansible|
	ansible.compatibility_mode = "2.0"
	ansible.playbook = "provisioning/playbook.yml"
	ansible.become = "true"
    end

end
