---
# tasks file for roles/pam_sudo

- name: add-sudo | Add {{ user_sudo }} to sudoers without password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ item }} ALL='
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - "{{ user_sudo }}"
  tags:
    - add-user-sudo

