---
- hosts: all
  become: true
  tasks:
  - name: install packages
    yum: 
      name:
        - bind
        - bind-utils
        - ntp
      state: present

  - name: copy transferkeys to all servers and the client
    copy: src={{ item }} dest=/etc/ owner=root group=named mode=0644
    with_fileglob:
      - named.zonetransfer*.key

- hosts: ns01
  become: true
  tasks:
  - name: copy named.conf
    copy: src=master-named.conf dest=/etc/named.conf owner=root group=named mode=0640

  - name: copy zones
    copy: src={{ item }} dest=/etc/named/ owner=root group=named mode=0660
    with_fileglob:
      - named.d*
      - client.named.d*
      - named.newdns*

  - name: copy resolv.conf to the servers
    copy: src=servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=1770

  - name: permission bind to modify zones in /etc/named
    sefcontext:
      target: '/etc/named(/.*)?'
      setype: named_zone_t
      state: present

  - name: apply new SELinux file context to /etc/named
    command: restorecon -irv /etc/named

  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes

- hosts: ns02
  become: true
  tasks:
  - name: copy named.conf
    copy: src=slave-named.conf dest=/etc/named.conf owner=root group=named mode=0640

  - name: copy slave zones include files for named.conf
    copy: src={{ item }} dest=/etc/named/ owner=root group=named mode=0660
    with_fileglob:
      - slave.named.*

  - name: copy resolv.conf to the servers
    copy: src=servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=1770

  - name: permission bind to modify zones in /etc/named
    sefcontext:
      target: '/etc/named(/.*)?'
      setype: named_zone_t
      state: present

  - name: apply new SELinux file context to filesystem
    command: restorecon -irv /etc/named

  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes

- hosts: client*
  become: true
  tasks:
  - name: copy resolv.conf to the client
    copy: src=client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: copy rndc conf file
    copy: src=rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644

  - name: copy motd to the client
    copy: src=client-motd dest=/etc/motd owner=root group=root mode=0644

