---
- name: install and configure ipa server
  hosts: ipaserver
  become: true
  roles:
    - ipa-server

- name: install and configure ipa client
  hosts: ipaclient
  become: true
  roles:
    - ipa-client
